name: epandozi
favicon: null
layout_spectrum: 0.41588505264371634
typography_spectrum: 0.2898489364888519
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#97011c'
    - '#100003'
    - '#5e3ffd'
    - '#ff6160'
    - '#ffbe51'
  brandStrength: 0.75
  lightness: 0.9404594227671623
  saturation: 0.4815843412652612
  rhythmicContrast: 0.19376344373449683
purpose: []
