typography_spectrum: 0.78691
color:
  brandColors:
    - '#e1eae5'
    - '#314754'
    - '#1b2d37'
    - '#b7c5c4'
    - '#625d5a'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.4815843412652612
  rhythmicContrast: 0.19376344373449683
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.41588505264371634
analytics:
  google: null
  facebook: null
  twitter: null
name: Evigma
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: My site
    url: evelynpandozi.me
    type: external
favicon: null
title: Spun
purpose: []
