name: epandozi
favicon: null
layout_spectrum: 0.41588505264371634
typography_spectrum: 0.2898489364888519
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9422130885068327
  lightness: 0.9404594227671623
  saturation: 0.4815843412652612
  rhythmicContrast: 0.19376344373449683
purpose: []
