name: epandozi
favicon: null
layout_spectrum: 0.41588505264371634
typography_spectrum: 0.78691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1eae5'
    - '#314754'
    - '#1b2d37'
    - '#b7c5c4'
    - '#625d5a'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.4815843412652612
  rhythmicContrast: 0.19376344373449683
purpose: []
